FROM node:22

WORKDIR /app

# Копируем package.json и package-lock.json
COPY yaml-generator-frontend/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
# Примечание: в docker-compose.yml мы монтируем локальную директорию,
# поэтому эта команда не нужна для разработки, но оставляем для полноты
COPY yaml-generator-frontend/ .

# Экспонируем порт
EXPOSE 4200

# Команда запуска (будет переопределена в docker-compose.yml)
CMD ["npm", "start"]
