version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8283:8283"
    environment:
      - ASPNETCORE_URLS=http://+:8283
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:4200"
    volumes:
      - ./frontend/yaml-generator-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - backend 